name = "foodsnap-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "foodsnap-db"
database_id = "db018196-c719-47a6-9ddf-c0bec7d8626f"

# Static assets (frontend)
[site]
bucket = "./public"

# R2 for image storage (optional)
# [[r2_buckets]]
# binding = "IMAGES"
# bucket_name = "foodsnap-images"

# Custom domain
[[routes]]
pattern = "foodsnap.duku.app/*"
zone_name = "duku.app"
